export const message = {
    "EMAIL_ALREADY_EXISTS":"Email already exists,   log in.",
    "MOBILE_ALREADY_EXISTS":"Mobile Number already exists,   log in.",
    "USERNAME_ALREADY_EXISTS":"Username already exists,   log in.",
    "UNABLE_TO_ADD_DETAILS":"Unable to add details.",
    "SIGNUP_SUCCESSFUL":"Signup Successful.",
    "USER_DOESNT_EXISTS":"This user doesn't exist",
    "USER_EXISTS":"This user exists",
    "SOCIAL_USER_NOT_FOUND":"Unable to find the social user.",
    "LOGIN_SUCCESSFUL":"Login successful.",
    "MISSING_VERIFICATION_CODE":"Verfication code is missing",
    "MISSING_EMAIL":"Email address is missing",
    "INVALID_VERIFICATION_CODE":"Invalid verification code.",
    "ACCOUNT_NOT_VERIFIED":"Unable to verify the account.",
    "ACCOUNT_VERIFIED":"Account is successfully verified.",
    "INVALID_CREDENTIALS":"Invalid credentials.",
    "OTP_SENT":"Successfully sent OTP",
    "PASSWORD_REQUIRED":"Password is required.",
    "EMAIL_MOBILE_REQUIRED":"Either email or mobile number is required",
    "DEVICE_TOKEN_REQUIRED":"Device token is required",
    "INCORRECT_PASSWORD":"Password is incorrect.",
    "VERIFY_ACCOUNT":"  verify your account.",
    "AWAITED_APPROVAL":"Waiting.. for Admin Approval",
    "BLOCKED_BY_ADMIN":"You have been blocked by the admin",
    "UNABLE_TO_UPDATE":"Unable to update user.",
    "SUCCESSFUL_PASSWORD_RESET":"Password resetted successfully.",
    "SUCCESSFUL_LOGOUT":"Successfully logged out.",
    "OLD_PASSWORD_INCORRECT":"Incorrect old password.",
    "PASSWORD_RESET_SUCCESSFUL":"Password reset successfully.",
    "EXPIRED_PROMO_CODE":"Your promo code has been expired.",
    "EXEEDED_LIMIT_PROMO":"Promo code limit has been exeeded.",
    "PROMO_APPLIED":"Promo code applied successfully",
    "FIRST_NAME_REQUIRED":"First name is required",
    "LAST_NAME_REQUIRED":"Last name is required",
    "COUNTRY_CODE_REQUIRED":"Country code is required",
    "EMAIL_REQUIRED":"Email is required",
    "MOBILE_REQUIRED":"Mobile is required",
    "USERNAME_REQUIRED":"Username is required.",
    "DEVICE_TYPE_REQUIRED":"Device type is required",
    "SOCIAL_EXISTS":"A social account with this email already exists",
    "ADDRESS_ADD_UNSUCCESSFUL":"Could not add address",
    "ADDRESS_ADD_SUCCESSFUL":"Added address successfully.",
    "ADDRESS_UPDATE_UNSUCCESSFUL":"Could not update address",
    "ADDRESS_UPDATE_SUCCESSFUL":"updated address successfully.",
    "ADDRESS_DELETE_UNSUCCESSFUL":"Address not found.",
    "ADDRESS_DELETE_SUCCESSFUL":"Deleted address successfully.",
    "ADDRESS_ID_MISSING":"address_id missing.",
    "LAT_LONG_MISSING":"Either latitude or longitude is missing",
    "ADDRESS_FETCH_SUCCESSFUL":"Successfully fetched addresses",
    "ADDRESS_FETCH_UNSUCCESSFUL":"No addresses found",
    "BANK_FETCH_SUCCESS":"Bank details fetched successfully",
    "BANK_UPDATE_SUCCESS": "Bank details updated successfully",
    "BANK_UPDATE_UNSUCCESS": "Bank details could not be updated",
    "NO_BANK_DETAILS":"No bank details found" ,
    "SUCCESSFUL" : "Successfully done" ,
    "ITEMSUCCESSFUL" : "Add Item Successfully",
    "CART_SUCCESS":"Added to Cart",
    "CART_COULD_NOT_CREATE":"Could not add to cart",
    "COMMON_SUCCESS":"Successful.",
    "COMMON_UNSUCCESS":"Unsuccessful.",
    "ITEM_ALREADY_EXISTS":"Item already exists",
    "SUCCESS_ITEM_FAVOURITE":"Item added as favourites",
    "FAVOURITE_ITEM_REMOVED":"Item removed from faourites",
    "SUCCESS_WATCH_LIST":"Item added to watched list",
    "REMOVED_WATCH_LIST":"Item removed from watch list",
    "ALREADY_IN_CART":"Item already added in cart",
    "BID_EXPIRE": "Bidding time expire",
    "STARTING_BID": "Bidding amount is less than product starting bid",
    "SOLD" :"Out of stock",
    "COULD_NOT_FIND_PRODUCT":"The item you are trying to add does not exist",
    "DIFFERENT_SELLERS":"You cant add products from different sellers in your cart",
    "COUNTRY_CODE_MISSING":"Country Code is missing",
    "MOBILE_MISSING":"Mobile Number is missing",
    "EMAIL_MISSING":"Email is missing",
    "Login":"Successfully Login"
}